config/routes.rb
Rails.application.routes.draw do

  get 'profile/index'

  devise_for :users, :controllers => {:registrations => "user/registrations"}
  root 'welcome#index'

  resources :jobs
  resources :welcome, except: [:destroy, :edit, :update, :show, :new, :create]

  get '/profile', to: 'profile#index'
  get '/profile/add_skill', to: 'profile#add_skill'
  get '/profile/remove_skill', to: 'profile#remove_skill'

  get '/job/employee_apply_to_job', to: 'jobs#employee_apply_to_job'
  get '/assign_jobs', to: 'jobs#assign_jobs'
  get '/job/assign_employee', to: 'jobs#assign_employee'

end

app/views/shared/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">

  <div class='col-lg-2'>
    <a class="navbar-brand" href="#">Employee Database</a>
  </div>

  <% if current_user %>

    <div class='col-lg-4'>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to("Profile", profile_path) %></li>
          <% if current_user.group_id == 1 %>
            <li><%= link_to("Assign Jobs", '/assign_jobs') %></li>
          <% elsif current_user.group_id ==2 %>
            <li><%= link_to("Add Job Listing", new_job_path) %></li>
            <li><%= link_to("Show your Job Listings", jobs_path) %></li>
          <% else %>
            <li><%= link_to("Check Job Listings", jobs_path) %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class='col-lg-3'></div>

    <div class='col-lg-3'>
      <br>
      <div class='navbar-collapse collapse navbar-responsive-collapse'>
        <ul class="nav navbar-nav">
          <li><i class="fa fa-user"></i><small><%= current_user.email %></small></li>
          <li style="padding: 5px;"> </li>
        </ul>
        <span style='border: 1px;'><%= link_to("Sign Out", destroy_user_session_path, method: :delete, class: 'logout_button') %></span>
      </div>
    </div>

  <% end %>

</div>